name: seahorse-app
region: New York  
workers:  
  - name: worker  
    environment_slug: python  
    github:  
      repo: katsully/chatgpt-discord-bot 
      branch: main  
    instance_count: 1  
    instance_size_slug: basic-xxs 